### ISSUE TITLE
Installation path conflict to different versions of python

### ISSUE THREAD

**Issue by machinatoonist** [fastai/paperspace-setup#2]
I ran this script on Paperspace and duplicated what was demonstrated on the video.  As a previous user of Paperspace running python3.9 this is aliased in the .bashrc file in the root directory as:
`alias python=python3.9`
`alias python3=python3.9`

But when running `mambai install fastai` or `pipi install universal-ctags` these are now installed in `/.local/lib/python3.7/site-packages` instead of `/.local/lib/python3.9/site-packages`

**Comment by jph00** [comment]
Yes the image paperspace is using is a mess. I've asked them if we can take over managing it.

The issue is that notebooks are running on python 3.7. The alias they've set is just messing python in the terminal up.

**Comment by jph00** [comment]
(BTW this stuff is best discussed on the forum.)
